repos:
  - repo: local
    files: ^signwriting_description/
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
      - id: pytest
        name: pytest
        entry: pytest signwriting_description
        language: system
        types: [python]

